baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'site'
theme = 'lugo'

[[menu.main]]
  name = "Home"
  url = '/'
  weight = 0


[[menu.main]]
  name = "about"
  url = '/me'
  weight = 1


