baseURL = 'https://www.jitendradara.workers.dev'
languageCode = 'en-us'
title = 'Portfolio'
theme = 'lugo'

[deployment]
  [[deployment.targets]]
    name = 'production'
    url = 'www.jitendradara.workers.dev'

[[menu.main]]
  name = "Home"
  url = '/'
  weight = 0


[[menu.main]]
  name = "about"
  url = '/me'
  weight = 1


